#ifndef LC32_CORE_GRAPHICS_BRIDGE_H
#define LC32_CORE_GRAPHICS_BRIDGE_H

#include <stdint.h>

enum {
    LC32CoreGraphicsABIVersion = 1,
    LC32CoreGraphicsMaxSlots = 16,
    LC32CoreGraphicsMaximumFilenameBytes = 64 * 1024,
};

typedef struct {
    uint32_t version;
    uint32_t slotCount;
    uint64_t slots[LC32CoreGraphicsMaxSlots];
} LC32CoreGraphicsCall;

typedef enum : uint32_t {
    LC32CoreGraphicsOpBitmapContextCreate = 1,
    LC32CoreGraphicsOpColorSpaceCreateDeviceRGB = 2,
    LC32CoreGraphicsOpColorSpaceRelease = 3,
    LC32CoreGraphicsOpContextClearRect = 4,
    LC32CoreGraphicsOpContextDrawImage = 5,
    LC32CoreGraphicsOpContextRelease = 6,
    LC32CoreGraphicsOpContextTranslateCTM = 7,
    LC32CoreGraphicsOpImageGetHeight = 8,
    LC32CoreGraphicsOpImageGetWidth = 9,
    LC32CoreGraphicsOpImageRelease = 10,
    LC32CoreGraphicsOpColorGetColorSpace = 11,
    LC32CoreGraphicsOpColorGetNumberOfComponents = 12,
    LC32CoreGraphicsOpColorCopyComponents = 13,
    LC32CoreGraphicsOpColorSpaceGetModel = 14,
    LC32CoreGraphicsOpDataProviderCreateWithFilename = 15,
    LC32CoreGraphicsOpImageCreateWithJPEGDataProvider = 16,
    LC32CoreGraphicsOpImageCreateWithPNGDataProvider = 17,
    LC32CoreGraphicsOpPathCreateMutable = 18,
    LC32CoreGraphicsOpPathAddLineToPoint = 19,
    LC32CoreGraphicsOpPathContainsPoint = 20,
    LC32CoreGraphicsOpPathMoveToPoint = 21,
    LC32CoreGraphicsOpPathCloseSubpath = 22,
    LC32CoreGraphicsOpPathRelease = 23,
    LC32CoreGraphicsOpColorCreate = 24,
    LC32CoreGraphicsOpColorGetAlpha = 25,
    LC32CoreGraphicsOpColorSpaceCreateDeviceGray = 26,
    LC32CoreGraphicsOpBitmapContextCreateImage = 27,
    LC32CoreGraphicsOpContextSaveGState = 28,
    LC32CoreGraphicsOpContextRestoreGState = 29,
    LC32CoreGraphicsOpContextBeginPath = 30,
    LC32CoreGraphicsOpContextClosePath = 31,
    LC32CoreGraphicsOpContextMoveToPoint = 32,
    LC32CoreGraphicsOpContextAddLineToPoint = 33,
    LC32CoreGraphicsOpContextAddArc = 34,
    LC32CoreGraphicsOpContextAddArcToPoint = 35,
    LC32CoreGraphicsOpContextAddRect = 36,
    LC32CoreGraphicsOpContextAddPath = 37,
    LC32CoreGraphicsOpContextClip = 38,
    LC32CoreGraphicsOpContextClipToMask = 39,
    LC32CoreGraphicsOpContextFillPath = 40,
    LC32CoreGraphicsOpContextFillRect = 41,
    LC32CoreGraphicsOpContextStrokePath = 42,
    LC32CoreGraphicsOpContextStrokeRect = 43,
    LC32CoreGraphicsOpContextScaleCTM = 44,
    LC32CoreGraphicsOpContextConcatCTM = 45,
    LC32CoreGraphicsOpContextSetFillColorWithColor = 46,
    LC32CoreGraphicsOpContextSetStrokeColorWithColor = 47,
    LC32CoreGraphicsOpContextSetGrayFillColor = 48,
    LC32CoreGraphicsOpContextSetBlendMode = 49,
    LC32CoreGraphicsOpContextSetInterpolationQuality = 50,
    LC32CoreGraphicsOpContextSetLineCap = 51,
    LC32CoreGraphicsOpContextSetLineWidth = 52,
    LC32CoreGraphicsOpContextSetShouldAntialias = 53,
    LC32CoreGraphicsOpContextSetTextPosition = 54,
    LC32CoreGraphicsOpImageCreateWithImageInRect = 55,
    LC32CoreGraphicsOpImageCreateWithMask = 56,
    LC32CoreGraphicsOpImageGetAlphaInfo = 57,
    LC32CoreGraphicsOpImageGetBitmapInfo = 58,
    LC32CoreGraphicsOpImageGetBitsPerComponent = 59,
    LC32CoreGraphicsOpImageGetColorSpace = 60,
    LC32CoreGraphicsOpPathAddArcToPoint = 61,
    LC32CoreGraphicsOpPathAddCurveToPoint = 62,
    LC32CoreGraphicsOpPathAddRect = 63,
    LC32CoreGraphicsOpPathCreateCopy = 64,
    LC32CoreGraphicsOpGradientCreateWithColorComponents = 65,
    LC32CoreGraphicsOpGradientCreateWithColors = 66,
    LC32CoreGraphicsOpContextDrawLinearGradient = 67,
    LC32CoreGraphicsOpContextSetFillColor = 68,
    LC32CoreGraphicsOpContextSetStrokeColorSpace = 69,
    LC32CoreGraphicsOpContextSetStrokeColor = 70,
    LC32CoreGraphicsOpContextStrokeLineSegments = 71,
    LC32CoreGraphicsOpImageGetBitsPerPixel = 72,
    LC32CoreGraphicsOpBitmapContextGetBytesPerRow = 73,
    LC32CoreGraphicsOpBitmapContextGetData = 74,
    LC32CoreGraphicsOpContextDrawPath = 75,
    LC32CoreGraphicsOpContextRotateCTM = 76,
    LC32CoreGraphicsOpImageGetBytesPerRow = 77,
    LC32CoreGraphicsOpContextAddEllipseInRect = 78,
    LC32CoreGraphicsOpContextClipToRect = 79,
    LC32CoreGraphicsOpContextDrawRadialGradient = 80,
    LC32CoreGraphicsOpContextFillEllipseInRect = 81,
    LC32CoreGraphicsOpContextSetRGBFillColor = 82,
    LC32CoreGraphicsOpContextSetRGBStrokeColor = 83,
    LC32CoreGraphicsOpContextSetShadowWithColor = 84,
    LC32CoreGraphicsOpContextStrokeEllipseInRect = 85,
    LC32CoreGraphicsOpDataProviderCreateWithCFData = 86,
    LC32CoreGraphicsOpImageCreateCopy = 87,
    LC32CoreGraphicsOpImageGetDataProvider = 88,
    LC32CoreGraphicsOpContextSetShadow = 89,
    LC32CoreGraphicsOpContextSetGrayStrokeColor = 90,
    LC32CoreGraphicsOpContextAddLines = 91,
    LC32CoreGraphicsOpContextSetLineJoin = 92,
    LC32CoreGraphicsOpContextSetTextMatrix = 93,
    LC32CoreGraphicsOpPathGetBoundingBox = 94,
    LC32CoreGraphicsOpImageCreate = 95,
    LC32CoreGraphicsOpContextSetAlpha = 96,
} LC32CoreGraphicsOpcode;

#endif
